In [1]:
import torch

In [35]:
# Создайте случайный FloatTensor размера 3x4x5
a = torch.randn(3,4,5)
a

tensor([[[ 1.1124,  0.1845, -1.8521,  0.2857,  0.0033],
         [ 0.1074, -1.2054,  0.6336, -2.3980, -0.7716],
         [-0.9325, -0.4101,  1.2943,  0.2747,  1.4973],
         [ 0.2940, -0.3792,  0.5216,  1.3667,  0.4662]],

        [[ 2.0720,  1.8968,  1.4773, -1.2425,  0.7276],
         [ 0.3901, -0.0537, -0.5280, -0.4175, -0.9172],
         [ 0.7078, -0.1583, -0.9152, -0.4675, -0.0669],
         [ 0.0378,  1.0691, -1.7804, -0.9508, -0.1547]],

        [[-1.6829, -0.8030, -0.7272,  1.4116,  0.7631],
         [-0.6005, -0.9773,  1.1596,  1.2583, -1.3904],
         [-0.3897, -0.5352, -1.2515,  0.2734,  1.1575],
         [ 1.5165,  0.3464,  2.1588, -0.4107, -0.2493]]])

In [36]:
# Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [37]:
# Приведите его к форме 6 X 10
a = a.reshape(6,10)

In [38]:
a.shape

torch.Size([6, 10])

In [41]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно

b = torch.IntTensor([1, 4, 2, 2, 1])
a.shape, b.shape

(torch.Size([6, 10]), torch.Size([5]))

In [ ]:
# === нельзя перемножать тензоры разных размерностей

In [43]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
a = torch.matmul(a, a.T)
a.shape

torch.Size([6, 6])

In [47]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

# dy/dx = 3x**2
# dy/dz = 1
# dy/dt = -75

# производная в т. (1, 0.5, 2) = (3, 1, -75)

In [50]:
# Создайте единичный тензор размера 5x6
c = torch.zeros((5,6)).fill_(1)
c

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [51]:
# Переведите его в формат numpy
c.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)